import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "@/store/Providers";
import { inter } from "@/config/font";
//import "bootstrap/dist/css/bootstrap.min.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
